"addi t1, zero, 8\n\t"
"vsetvli t0, t1, e16, ta, ma\n\t"
"vle16.v v1, (%0) \n\t"
"L1:\n\t"
"lw  t2, 0(%0)   \n\t"
"vadd.vx v2, v1, t2 \n\t"
"vmseq.vx v3, v2, %[target] \n\t"
"vse16.v v3, (%1)\n\t"
"lw t3, 0(%1)\n\t"
"slt t4, zero, t3\n\t"
"bnez t4, True\n\t"
"addi %0, %0, 2\n\t"
"addi t1, t1, -1\n\t"
"bnez t1, L1\n\t"
"j False\n\t"
"True:\n\t"
"addi %[flag], zero, 1\n\t"
"False:\n\t"
