"addi t0, zero, 0\n\t"     
"addi t2, zero, 16\n"  
"addi %[arith_cnt], %[arith_cnt], 2\n\t" 
"loop:\n\t" 
"lw t3, 0(%[x])\n\t"    
"lw t4, 0(%[h])\n\t"    
"add t3, t3, t4\n\t"    
"sw t3, 0(%[y])\n\t"    
"addi %[x], %[x], 2\n\t"  
"addi %[h], %[h], 2\n\t"  
"addi %[y], %[y], 2\n\t"  
"addi t0, t0, 1\n\t"      
"addi %[arith_cnt], %[arith_cnt], 5\n\t" 
"addi %[lw_cnt], %[lw_cnt], 2\n\t" 
"addi %[sw_cnt], %[sw_cnt], 1\n\t" 
"addi %[others_cnt], %[others_cnt], 1\n\t" 
"bne t0, t2, loop\n\t"              
"exit:\n\t"